### ISSUE TITLE
ActorService JSON improvements

### ISSUE THREAD

**Issue by meany** [tangramproject/Cypher#3]
I noticed a lot of `JObject.Parse` in `ActorService.cs`, like so:
```
return JObject.Parse(@"{success: true, message: { previous:" + previousBal + ", available:" + availableBal + "}}");
```
This could be refactored to use `FromObject` to work like this:
```
return JObject.FromObject(new
{
    success = true,
    message = new
    {
        previous = previousBal,
        available = availableBal
    }
});
```
This will improve code readability and cut down on string concatenation. This could also prevent future runtime issues with JSON text that does not parse.

I can fix it up and submit the PR.

**Comment by pingpongsneak** [comment]
Make it so...

**Comment by meany** [comment]
https://github.com/tangramproject/Cypher/pull/5
